packages:
  - apps/*
  - pkgs/*

catalog:
  turbo: ^2.6.1
  '@biomejs/biome': ^2.3.5
  typescript: ^5.9.3
  tsx: ^4.20.6
  zod: 4.1.12
  neverthrow: 8.2.0
  vitest: ^4.0.8
  vite-tsconfig-paths: ^5.1.4
  '@aws-sdk/client-cognito-identity-provider': ^3.932.0
  '@hono/node-server': ^1.19.6
  '@hono/zod-validator': ^0.7.4
  hono: ^4.10.6
  ts-pattern: 5.9.0
  '@types/node': 24.10.1
  '@prisma/client': ^7.0.0
  aws-jwt-verify: ^5.1.1
  prisma: ^7.0.0
  prisma-erd-generator: ^2.3.0
  '@prisma/config': ^7.0.0

catalogMode: prefer

managePackageManagerVersions: true

minimumReleaseAge: 10080
