packages:
  - apps/*
  - pkgs/*

catalog:
  turbo: ^2.6.1
  '@biomejs/biome': ^2.3.5
  typescript: ^5.9.3
  tsx: ^4.20.6
  zod: ^4.1.12
  neverthrow: ^8.2.0
  vitest: ^4.0.8
  vite-tsconfig-paths: ^5.1.4

catalogMode: prefer

managePackageManagerVersions: true

minimumReleaseAge: 10080
